### ISSUE TITLE
panic: runtime error with unknown user

### ISSUE THREAD

**Issue by srfraser** [joushou/sshmuxd#7]
Built from source on 28th Sept 2015 using go1.4.2 on Linux Mint 17 (Ubuntu derivative), when I connect to sshmuxd as a user that does not have an entry in the authkeys file, and there is a configuration entry that has `"noAuth": true` set, then there is a runtime error. Ideally this should be handled gracefully to prevent a denial of service.

conf.json:

```
{
   "address": ":2222",
   "hostkey": "hostkey",
   "authkeys": "authkeys",
   "hosts": [
      {
         "address": "internal.hostname.com:22",
         "noAuth": true
      }
   ]
}

```

User sees:

```
$ ssh -p 2222 localhost
Write failed: Broken pipe
```

Server's stdout:

```
$ ./sshmuxd conf.json 
2015/09/28 13:16:54 127.0.0.1:55898: unknown user authorized (username: srf)
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4029b6]

goroutine 5 [running]:
main.func·003(0xc20805a380, 0xc20803cd20, 0x24, 0x0, 0x0)
    /home/simon/.gvm/pkgsets/go1.4.2/global/src/github.com/joushou/sshmuxd/main.go:165 +0x216
github.com/joushou/sshmux.(*Server).SessionForward(0xc20803da40, 0xc20805a380, 0x7f2e79b25d50, 0xc20806e0c0, 0xc208052480)
    /home/simon/.gvm/pkgsets/go1.4.2/global/src/github.com/joushou/sshmux/forward.go:163 +0x2c4
github.com/joushou/sshmux.(*Server).HandleConn(0xc20803da40, 0x7f2e79b25500, 0xc208030040)
    /home/simon/.gvm/pkgsets/go1.4.2/global/src/github.com/joushou/sshmux/server.go:122 +0x5f9
created by github.com/joushou/sshmux.(*Server).Serve
    /home/simon/.gvm/pkgsets/go1.4.2/global/src/github.com/joushou/sshmux/server.go:139 +0x9f

goroutine 1 [IO wait]:
net.(*pollDesc).Wait(0xc2080101b0, 0x72, 0x0, 0x0)
    /home/simon/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc2080101b0, 0x0, 0x0)
    /home/simon/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).accept(0xc208010150, 0x0, 0x7f2e79b23a20, 0xc20802a958)
    /home/simon/.gvm/gos/go1.4.2/src/net/fd_unix.go:419 +0x40b
net.(*TCPListener).AcceptTCP(0xc208030038, 0xc208087dd0, 0x0, 0x0)
    /home/simon/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:234 +0x4e
net.(*TCPListener).Accept(0xc208030038, 0x0, 0x0, 0x0, 0x0)
    /home/simon/.gvm/gos/go1.4.2/src/net/tcpsock_posix.go:244 +0x4c
github.com/joushou/sshmux.(*Server).Serve(0xc20803da40, 0x7f2e79b244b8, 0xc208030038, 0x0, 0x0)
    /home/simon/.gvm/pkgsets/go1.4.2/global/src/github.com/joushou/sshmux/server.go:134 +0x40
main.main()
    /home/simon/.gvm/pkgsets/go1.4.2/global/src/github.com/joushou/sshmuxd/main.go:175 +0x55a

goroutine 6 [IO wait]:
net.(*pollDesc).Wait(0xc208010220, 0x72, 0x0, 0x0)
    /home/simon/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:84 +0x47
net.(*pollDesc).WaitRead(0xc208010220, 0x0, 0x0)
    /home/simon/.gvm/gos/go1.4.2/src/net/fd_poll_runtime.go:89 +0x43
net.(*netFD).Read(0xc2080101c0, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x7f2e79b23a20, 0xc20802a920)
    /home/simon/.gvm/gos/go1.4.2/src/net/fd_unix.go:242 +0x40f
net.(*conn).Read(0xc208030040, 0xc20800f000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
    /home/simon/.gvm/gos/go1.4.2/src/net/net.go:121 +0xdc
bufio.(*Reader).fill(0xc208052060)
    /home/simon/.gvm/gos/go1.4.2/src/bufio/bufio.go:97 +0x1ce
bufio.(*Reader).Read(0xc208052060, 0xc2080563a0, 0x5, 0x5, 0xc2080100e0, 0x0, 0x0)
    /home/simon/.gvm/gos/go1.4.2/src/bufio/bufio.go:174 +0x26c
io.ReadAtLeast(0x7f2e79b25710, 0xc208052060, 0xc2080563a0, 0x5, 0x5, 0x5, 0x0, 0x0, 0x0)
    /home/simon/.gvm/gos/go1.4.2/src/io/io.go:298 +0xf1
io.ReadFull(0x7f2e79b25710, 0xc208052060, 0xc2080563a0, 0x5, 0x5, 0x454, 0x0, 0x0)
    /home/simon/.gvm/gos/go1.4.2/src/io/io.go:316 +0x6d
golang.org/x/crypto/ssh.(*streamPacketCipher).readPacket(0xc208056380, 0xc200000008, 0x7f2e79b25710, 0xc208052060, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/simon/.gvm/pkgsets/go1.4.2/global/src/golang.org/x/crypto/ssh/cipher.go:142 +0xd4
golang.org/x/crypto/ssh.(*connectionState).readPacket(0xc208001200, 0xc208052060, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/simon/.gvm/pkgsets/go1.4.2/global/src/golang.org/x/crypto/ssh/transport.go:111 +0xe1
golang.org/x/crypto/ssh.(*transport).readPacket(0xc208001200, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/simon/.gvm/pkgsets/go1.4.2/global/src/golang.org/x/crypto/ssh/transport.go:107 +0x68
golang.org/x/crypto/ssh.(*handshakeTransport).readOnePacket(0xc208001320, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/simon/.gvm/pkgsets/go1.4.2/global/src/golang.org/x/crypto/ssh/handshake.go:165 +0x101
golang.org/x/crypto/ssh.(*handshakeTransport).readLoop(0xc208001320)
    /home/simon/.gvm/pkgsets/go1.4.2/global/src/golang.org/x/crypto/ssh/handshake.go:145 +0x28
created by golang.org/x/crypto/ssh.newServerTransport
    /home/simon/.gvm/pkgsets/go1.4.2/global/src/golang.org/x/crypto/ssh/handshake.go:120 +0xea

goroutine 7 [chan receive]:
golang.org/x/crypto/ssh.(*handshakeTransport).readPacket(0xc208001320, 0x0, 0x0, 0x0, 0x0, 0x0)
    /home/simon/.gvm/pkgsets/go1.4.2/global/src/golang.org/x/crypto/ssh/handshake.go:136 +0x8a
golang.org/x/crypto/ssh.(*mux).onePacket(0xc2080103f0, 0x0, 0x0)
    /home/simon/.gvm/pkgsets/go1.4.2/global/src/golang.org/x/crypto/ssh/mux.go:224 +0x67
golang.org/x/crypto/ssh.(*mux).loop(0xc2080103f0)
    /home/simon/.gvm/pkgsets/go1.4.2/global/src/golang.org/x/crypto/ssh/mux.go:199 +0x49
created by golang.org/x/crypto/ssh.newMux
    /home/simon/.gvm/pkgsets/go1.4.2/global/src/golang.org/x/crypto/ssh/mux.go:128 +0x19c

goroutine 8 [chan receive]:
golang.org/x/crypto/ssh.DiscardRequests(0xc208052540)
    /home/simon/.gvm/pkgsets/go1.4.2/global/src/golang.org/x/crypto/ssh/connection.go:81 +0x51
created by github.com/joushou/sshmux.(*Server).HandleConn
    /home/simon/.gvm/pkgsets/go1.4.2/global/src/github.com/joushou/sshmux/server.go:113 +0x426

```

**Comment by kennylevinsen** [comment]
I'll take a look right away!

**Comment by kennylevinsen** [comment]
It was a missing nil-check on the User field of the session when logging the final connection that was to blame. Should be fixed in master. Please test!

EDIT: There's still something...

**Comment by kennylevinsen** [comment]
Okay, there was another nil-check (generation of permitted remote list also didn't check nil-check the User field before using it...). I was a bit too fast there. I can authenticate with unknown users now without any issues. I'll close this issue, but please do not hesitate to open more issues if you find any.

Thanks for helping with the bug report!

**Comment by kennylevinsen** [comment]
Made a 0.1.1 release for this.
